export default {
    CARGAR_TEST : 'CARGAR_TEST',
    GET_ESTRENOS: 'GET_ESTRENOS',
    GET_ESTRENOS_FULFILLED: 'GET_ESTRENOS_FULFILLED',
    GET_PROXIMOS_ESTRENOS: 'GET_PROXIMOS_ESTRENOS',
    GET_PROXIMOS_ESTRENOS_FULFILLED: 'GET_PROXIMOS_ESTRENOS_FULFILLED',
    GET_PELICULA:'GET_PELICULA',
    GET_PELICULA_FULFILLED:'GET_PELICULA_FULFILLED',
    GET_CAST_PELICULA:'GET_CAST_PELICULA',
    GET_CAST_PELICULA_FULFILLED:'GET_CAST_PELICULA_FULFILLED',
    SEARCH_MOVIES:'SEARCH_MOVIES',
    SEARCH_MOVIES_FULFILLED:'SEARCH_MOVIES_FULFILLED',
    CLEAN_SEARCH: 'CLEAN_SEARCH'
}